import {defineField, defineType} from 'sanity'

const requiredText = (name: string, title: string, initialValue?: string) =>
  defineField({
    name,
    title,
    type: 'string',
    initialValue,
    validation: Rule => Rule.required(),
  })

const imageField = (name: string, title: string) =>
  defineField({
    name,
    title,
    type: 'image',
    options: {hotspot: true},
    fields: [defineField({name: 'alt', title: 'Alternativer Text', type: 'string'})],
  })

export default defineType({
  name: 'siteSettings',
  title: 'Website-Einstellungen',
  type: 'document',
  initialValue: {
    siteName: 'Metal im Dorf',
    accentColorPicker: {_type: 'color', hex: '#00A8BB', alpha: 1},
    accentTextColorPicker: {_type: 'color', hex: '#050505', alpha: 1},
    defaultSeo: {
      title: 'Metal im Dorf',
      description: 'News und aktuelle Infos vom Metal im Dorf Festival.',
    },
    hero: {
      kicker: 'Small festival, heavy sound',
      title: 'Metal im Dorf',
      intro:
        'Das kleine Metal-Festival am Opfermoor Niederdorla: direkt, laut und ohne Umwege. Hier findest du aktuelle Ansagen, Bands und Rückblicke.',
      primaryButtonLabel: 'News lesen',
      secondaryButtonLabel: 'Line-Up ansehen',
      showPrimaryButton: true,
      showSecondaryButton: true,
      showNextEvent: true,
      nextEventLabel: 'Nächste Veranstaltung',
      eventDetailsLabel: 'Veranstaltungsdetails',
      ticketFallbackLabel: 'Tickets',
    },
    sections: {
      nextEvent: {
        kicker: 'Termine',
        title: 'Kommende Veranstaltungen',
        locationLabel: 'Ort',
        emptyText: 'Aktuell sind keine kommenden Veranstaltungen angekündigt.',
      },
      eventPosters: {
        kicker: 'Plakate',
        title: 'Kommende Veranstaltungen',
        description: 'Plakate und Termine der kommenden Metal im Dorf Veranstaltungen.',
        emptyText: 'Aktuell sind noch keine Veranstaltungsplakate verfügbar.',
      },
      news: {
        kicker: 'News',
        title: 'Aktuelles vom Festival',
        emptyText: 'Keine News verfügbar.',
        articleLabel: 'Artikel lesen',
        previousLabel: 'Zurück',
        nextLabel: 'Weiter',
        pageLabel: 'Seite',
      },
      lineup: {
        kicker: 'Live & laut',
        title: 'Line-Up',
        intro: 'Die Bands für das nächste Metal im Dorf.',
        emptyText: 'Das Line-Up wird bald bekanntgegeben.',
        placeholderGenre: 'Ankündigung folgt',
        placeholderName: 'Wird noch bekannt gegeben',
        defaultGenre: 'Metal',
        unknownTime: 'TBA',
        showRunningOrder: false,
        runningOrderKicker: 'Live-Zeiten',
        runningOrderTitle: 'Running Order',
        runningOrderEmptyText: 'Die Running Order wird noch bekanntgegeben.',
      },
      history: {
        kicker: 'Archiv',
        title: 'Historie',
        intro:
          'Poster, Rückblicke und Impressionen vergangener Festivals und Nebenveranstaltungen.',
        emptyText: 'Keine Einträge in der Historie verfügbar.',
        allFilterLabel: 'Alle',
        mainFilterLabel: 'Hauptfestival',
        sideFilterLabel: 'Nebenveranstaltungen',
        filterEmptyText: 'In dieser Kategorie gibt es noch keine Einträge.',
      },
      eventDetail: {
        kicker: 'Veranstaltung',
        backLabel: 'Veranstaltungen',
        dateLabel: 'Termin',
        locationLabel: 'Ort',
        admissionLabel: 'Eintritt',
        routeLabel: 'Route',
        directionsLabel: 'Anfahrt',
        lineupKicker: 'Live',
        lineupTitle: 'Line-Up',
        infoKicker: 'Vor deinem Besuch',
        infoLabel: 'Anreise, Parken, Einlass und weitere Festival-Infos',
      },
      historyDetail: {
        backLabel: 'Zurück zur Übersicht',
        introTemplate: 'Impressionen und Archivmaterial vom Metal im Dorf {year}.',
        emptyText: 'Für dieses Jahr ist noch kein Rückblickstext vorhanden.',
        galleryKicker: 'Galerie',
        galleryTitle: 'Impressionen & Event-Fotos',
      },
      admin: {
        kicker: 'Verwaltung',
        title: 'Redaktionsbereich',
        intro: 'Hier geht es zur Verwaltung der Festivalinhalte.',
        buttonLabel: 'Sanity öffnen',
      },
    },
    navigation: {
      newsLabel: 'News',
      lineupLabel: 'Line-Up',
      eventsLabel: 'Veranstaltungen',
      infoLabel: 'Infos',
      historyLabel: 'Historie',
      legalLabel: 'Impressum',
      adminLabel: 'Adminbereich',
    },
    footer: {
      description:
        'Ein kleines, lautes Festival im Dorf: harte Riffs, kurze Wege und eine Community, die vor der Bühne zuhause ist.',
      navigationTitle: 'Navigation',
      contactTitle: 'Kontakt',
      socialTitle: 'Folge uns',
    },
    contact: {
      email: 'metalimdorf@gmx.de',
      address: ['Opfermoor Niederdorla', 'An der Oberrothe, 99988 Niederdorla'],
      instagramUrl: 'https://www.instagram.com/metalimdorf',
      facebookUrl: 'https://www.facebook.com/metalimdorf',
      showInstagram: true,
      showFacebook: true,
      studioUrl: 'https://metal-im-dorf.sanity.studio/',
    },
    notice: {
      enabled: false,
      text: 'Wichtiger Hinweis zum Festival',
      linkLabel: 'Mehr erfahren',
    },
  },
  groups: [
    {name: 'design', title: 'Design & SEO', default: true},
    {name: 'homepage', title: 'Startseite'},
    {name: 'pages', title: 'Seiten & Texte'},
    {name: 'navigation', title: 'Menü'},
    {name: 'footer', title: 'Footer & Kontakt'},
    {name: 'notice', title: 'Hinweisbanner'},
  ],
  fields: [
    defineField({...requiredText('siteName', 'Name der Website', 'Metal im Dorf'), group: 'design'}),
    defineField({
      name: 'accentColorPicker',
      title: 'Highlight-Farbe',
      description: 'Farbe auswählen oder als Hex-Wert eingeben.',
      type: 'color',
      group: 'design',
      options: {disableAlpha: true},
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'accentTextColorPicker',
      title: 'Textfarbe auf Highlights',
      description: 'Für helle Highlights dunkel, für dunkle Highlights hell wählen.',
      type: 'color',
      group: 'design',
      options: {disableAlpha: true},
      validation: Rule => Rule.required(),
    }),
    defineField({...imageField('logo', 'Logo'), group: 'design'}),
    defineField({
      name: 'defaultSeo',
      title: 'Standard für Suchmaschinen',
      type: 'object',
      group: 'design',
      fields: [
        requiredText('title', 'Seitentitel', 'Metal im Dorf'),
        defineField({
          name: 'description',
          title: 'Beschreibung',
          type: 'text',
          rows: 3,
          initialValue: 'News und aktuelle Infos vom Metal im Dorf Festival.',
        }),
        imageField('image', 'Vorschaubild beim Teilen'),
      ],
    }),
    defineField({
      name: 'hero',
      title: 'Hero auf der Startseite',
      type: 'object',
      group: 'homepage',
      fields: [
        imageField('image', 'Hintergrundbild'),
        requiredText('kicker', 'Kleine Überschrift', 'Small festival, heavy sound'),
        requiredText('title', 'Hauptüberschrift', 'Metal im Dorf'),
        defineField({
          name: 'intro',
          title: 'Einleitung',
          type: 'text',
          rows: 3,
          initialValue:
            'Das kleine Metal-Festival am Opfermoor Niederdorla: direkt, laut und ohne Umwege. Hier findest du aktuelle Ansagen, Bands und Rückblicke.',
        }),
        requiredText('primaryButtonLabel', 'Text des News-Buttons', 'News lesen'),
        requiredText('secondaryButtonLabel', 'Text des Line-up-Buttons', 'Line-Up ansehen'),
        defineField({
          name: 'showPrimaryButton',
          title: 'News-Button anzeigen',
          type: 'boolean',
          initialValue: true,
        }),
        defineField({
          name: 'showSecondaryButton',
          title: 'Line-up-Button anzeigen',
          type: 'boolean',
          initialValue: true,
        }),
        defineField({
          name: 'showNextEvent',
          title: 'Nächste Veranstaltung anzeigen',
          type: 'boolean',
          initialValue: true,
        }),
        requiredText('nextEventLabel', 'Beschriftung der Veranstaltung', 'Nächste Veranstaltung'),
        requiredText('eventDetailsLabel', 'Text des Detail-Links', 'Veranstaltungsdetails'),
        requiredText('ticketFallbackLabel', 'Tickettext ohne eigene Beschriftung', 'Tickets'),
      ],
    }),
    defineField({
      name: 'sections',
      title: 'Überschriften der Bereiche',
      type: 'object',
      group: 'pages',
      fields: [
        defineField({
          name: 'nextEvent',
          title: 'Kommende Veranstaltungen',
          type: 'object',
          fields: [
            requiredText('kicker', 'Kleine Überschrift', 'Termine'),
            requiredText('title', 'Überschrift', 'Kommende Veranstaltungen'),
            requiredText('locationLabel', 'Beschriftung des Orts', 'Ort'),
            requiredText(
              'emptyText',
              'Text ohne kommende Veranstaltungen',
              'Aktuell sind keine kommenden Veranstaltungen angekündigt.',
            ),
          ],
        }),
        defineField({
          name: 'eventPosters',
          title: 'Veranstaltungsplakate',
          type: 'object',
          fields: [
            requiredText('kicker', 'Kleine Überschrift', 'Plakate'),
            requiredText('title', 'Überschrift', 'Kommende Veranstaltungen'),
            requiredText(
              'description',
              'Beschreibung für Suchmaschinen',
              'Plakate und Termine der kommenden Metal im Dorf Veranstaltungen.',
            ),
            requiredText(
              'emptyText',
              'Text ohne Plakate',
              'Aktuell sind noch keine Veranstaltungsplakate verfügbar.',
            ),
          ],
        }),
        defineField({
          name: 'news',
          title: 'News',
          type: 'object',
          fields: [
            requiredText('kicker', 'Kleine Überschrift', 'News'),
            requiredText('title', 'Überschrift', 'Aktuelles vom Festival'),
            requiredText('emptyText', 'Text ohne Einträge', 'Keine News verfügbar.'),
            requiredText('articleLabel', 'Link zur vollständigen News', 'Artikel lesen'),
            requiredText('previousLabel', 'Vorherige News-Seite', 'Zurück'),
            requiredText('nextLabel', 'Nächste News-Seite', 'Weiter'),
            requiredText('pageLabel', 'Bezeichnung der Seitenzahl', 'Seite'),
          ],
        }),
        defineField({
          name: 'lineup',
          title: 'Line-Up',
          type: 'object',
          fields: [
            requiredText('kicker', 'Kleine Überschrift', 'Live & laut'),
            requiredText('title', 'Überschrift', 'Line-Up'),
            defineField({name: 'intro', title: 'Einleitung', type: 'text', rows: 2}),
            defineField({
              name: 'showRunningOrder',
              title: 'Running Order anzeigen',
              description: 'Zeigt die Spielzeiten oberhalb der Bandübersicht an.',
              type: 'boolean',
              initialValue: false,
            }),
            requiredText('runningOrderKicker', 'Kleine Überschrift der Running Order', 'Live-Zeiten'),
            requiredText('runningOrderTitle', 'Überschrift der Running Order', 'Running Order'),
            requiredText(
              'runningOrderEmptyText',
              'Text ohne eingetragene Spielzeiten',
              'Die Running Order wird noch bekanntgegeben.',
            ),
            requiredText('emptyText', 'Text ohne Einträge', 'Das Line-Up wird bald bekanntgegeben.'),
            requiredText('placeholderGenre', 'Text für offenen Slot', 'Ankündigung folgt'),
            requiredText('placeholderName', 'Name für offenen Slot', 'Wird noch bekannt gegeben'),
            requiredText('defaultGenre', 'Genre ohne Angabe', 'Metal'),
            requiredText('unknownTime', 'Spielzeit ohne Angabe', 'TBA'),
          ],
        }),
        defineField({
          name: 'history',
          title: 'Historie',
          type: 'object',
          fields: [
            requiredText('kicker', 'Kleine Überschrift', 'Archiv'),
            requiredText('title', 'Überschrift', 'Historie'),
            defineField({
              name: 'intro',
              title: 'Einleitung',
              type: 'text',
              rows: 2,
              initialValue:
                'Poster, Rückblicke und Impressionen vergangener Festivals und Nebenveranstaltungen.',
            }),
            requiredText('emptyText', 'Text ohne Einträge', 'Keine Einträge in der Historie verfügbar.'),
            requiredText('allFilterLabel', 'Filter: Alle', 'Alle'),
            requiredText('mainFilterLabel', 'Filter: Hauptfestival', 'Hauptfestival'),
            requiredText(
              'sideFilterLabel',
              'Filter: Nebenveranstaltungen',
              'Nebenveranstaltungen',
            ),
            requiredText(
              'filterEmptyText',
              'Text bei leerem Filter',
              'In dieser Kategorie gibt es noch keine Einträge.',
            ),
          ],
        }),
        defineField({
          name: 'eventDetail',
          title: 'Veranstaltungs-Unterseiten',
          type: 'object',
          fields: [
            requiredText('kicker', 'Kleine Überschrift', 'Veranstaltung'),
            requiredText('backLabel', 'Zurück-Link', 'Veranstaltungen'),
            requiredText('dateLabel', 'Beschriftung Termin', 'Termin'),
            requiredText('locationLabel', 'Beschriftung Ort', 'Ort'),
            requiredText('admissionLabel', 'Beschriftung Eintritt', 'Eintritt'),
            requiredText('routeLabel', 'Kleine Beschriftung der Anfahrt', 'Route'),
            requiredText('directionsLabel', 'Anfahrts-Link', 'Anfahrt'),
            requiredText('lineupKicker', 'Kleine Line-up-Überschrift', 'Live'),
            requiredText('lineupTitle', 'Line-up-Überschrift', 'Line-Up'),
            requiredText('infoKicker', 'Kleine Info-Überschrift', 'Vor deinem Besuch'),
            requiredText(
              'infoLabel',
              'Link zu den Festival-Infos',
              'Anreise, Parken, Einlass und weitere Festival-Infos',
            ),
          ],
        }),
        defineField({
          name: 'historyDetail',
          title: 'Historien-Unterseiten',
          type: 'object',
          fields: [
            requiredText('backLabel', 'Zurück-Link', 'Zurück zur Übersicht'),
            requiredText(
              'introTemplate',
              'Einleitung',
              'Impressionen und Archivmaterial vom Metal im Dorf {year}.',
            ),
            requiredText(
              'emptyText',
              'Text ohne Rückblick',
              'Für dieses Jahr ist noch kein Rückblickstext vorhanden.',
            ),
            requiredText('galleryKicker', 'Kleine Galerie-Überschrift', 'Galerie'),
            requiredText('galleryTitle', 'Galerie-Überschrift', 'Impressionen & Event-Fotos'),
          ],
        }),
        defineField({
          name: 'admin',
          title: 'Adminseite',
          type: 'object',
          fields: [
            requiredText('kicker', 'Kleine Überschrift', 'Verwaltung'),
            requiredText('title', 'Überschrift', 'Redaktionsbereich'),
            requiredText(
              'intro',
              'Einleitung',
              'Hier geht es zur Verwaltung der Festivalinhalte.',
            ),
            requiredText('buttonLabel', 'Buttontext', 'Sanity öffnen'),
          ],
        }),
      ],
    }),
    defineField({
      name: 'notice',
      title: 'Globaler Hinweisbanner',
      description: 'Für wichtige Hinweise wie Wetter, Einlass oder kurzfristige Änderungen.',
      type: 'object',
      group: 'notice',
      fields: [
        defineField({
          name: 'enabled',
          title: 'Hinweis anzeigen',
          type: 'boolean',
          initialValue: false,
        }),
        defineField({
          name: 'text',
          title: 'Hinweistext',
          type: 'string',
          validation: Rule => Rule.required(),
        }),
        defineField({name: 'linkLabel', title: 'Linktext', type: 'string'}),
        defineField({
          name: 'linkUrl',
          title: 'Link',
          description: 'Externe URL oder interner Pfad, zum Beispiel /infos.',
          type: 'string',
        }),
      ],
    }),
    defineField({
      name: 'navigation',
      title: 'Beschriftung der Navigation',
      type: 'object',
      group: 'navigation',
      fields: [
        requiredText('newsLabel', 'News', 'News'),
        requiredText('lineupLabel', 'Line-Up', 'Line-Up'),
        requiredText('eventsLabel', 'Veranstaltungen', 'Veranstaltungen'),
        requiredText('infoLabel', 'Festival-Infos', 'Infos'),
        requiredText('historyLabel', 'Historie', 'Historie'),
        requiredText('legalLabel', 'Impressum', 'Impressum'),
        requiredText('adminLabel', 'Adminbereich', 'Adminbereich'),
      ],
    }),
    defineField({
      name: 'footer',
      title: 'Footer',
      type: 'object',
      group: 'footer',
      fields: [
        defineField({
          name: 'description',
          title: 'Kurzbeschreibung',
          type: 'text',
          rows: 3,
          initialValue:
            'Ein kleines, lautes Festival im Dorf: harte Riffs, kurze Wege und eine Community, die vor der Bühne zuhause ist.',
        }),
        requiredText('navigationTitle', 'Überschrift Navigation', 'Navigation'),
        requiredText('contactTitle', 'Überschrift Kontakt', 'Kontakt'),
        requiredText('socialTitle', 'Überschrift Social Media', 'Folge uns'),
        defineField({name: 'copyright', title: 'Copyright-Text', type: 'string'}),
      ],
    }),
    defineField({
      name: 'contact',
      title: 'Kontakt & Social Media',
      type: 'object',
      group: 'footer',
      fields: [
        defineField({name: 'email', title: 'E-Mail', type: 'string', validation: Rule => Rule.email()}),
        defineField({name: 'address', title: 'Adresse', type: 'array', of: [{type: 'string'}]}),
        defineField({name: 'instagramUrl', title: 'Instagram-Link', type: 'url'}),
        defineField({
          name: 'showInstagram',
          title: 'Instagram anzeigen',
          type: 'boolean',
          initialValue: true,
        }),
        defineField({name: 'facebookUrl', title: 'Facebook-Link', type: 'url'}),
        defineField({
          name: 'showFacebook',
          title: 'Facebook anzeigen',
          type: 'boolean',
          initialValue: true,
        }),
        defineField({
          name: 'studioUrl',
          title: 'Link zum Adminbereich',
          type: 'url',
          initialValue: 'https://metal-im-dorf.sanity.studio/',
          validation: Rule => Rule.required(),
        }),
      ],
    }),
  ],
  preview: {
    prepare: () => ({title: 'Website-Einstellungen'}),
  },
})
